### ISSUE TITLE
Sample for Angular 

### ISSUE THREAD

**Issue by xts-velkumars** [dwarfcoder/xml-viewer-component#24]
Hi @dwarfcoder, 

Can you provide some sample for Angular. 

Did I need to import any modules ?

**Comment by alex-solx** [comment]
> Hi @dwarfcoder,
> 
> Can you provide some sample for Angular.
> 
> Did I need to import any modules ?

Hi Velkumar!

The work is undergo, please be patient. As a result I'll update the docs and provide a sample angular app. Be back soon

**Comment by alex-solx** [comment]
Well, I updated documentation, you can find it here: https://github.com/dwarfcoder/xml-viewer-component
Also added a simple angular demo app which uses an xml-viewer-component - https://github.com/dwarfcoder/xml-viewer-angular-demo. There is a readme describing everything you need to use this web component.

Long story short: steps you have to do to make this component work for you:

1. install and save component:
```
npm install xml-viewer-component --save
```

2. import CUSTOM_ELEMENTS_SCHEMA in your module (app.module.ts or any other module where this component should appear):
```javascript
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
```

3. Add schema section in @NgModule declaration:
```javascript
@NgModule({
    // ...
    schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
})
```

4. Call to *defineCustomElements()* function
```javascript
platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));

// add this line of code:
defineCustomElements(window);
```

5. Import xml-viewer-component inside of your component (app.component.ts for example):
```typescript
import 'xml-viewer-component';
```

that's it. Details in [this readme](https://github.com/dwarfcoder/xml-viewer-angular-demo/blob/main/README.md)
