### ISSUE TITLE
After installing version 0.4.0 the node modules folder keeps empty

### ISSUE THREAD

**Issue by NiDeWe** [dwarfcoder/xml-viewer-component#33]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
After I do a npm install en retrieving version 0.4.0 the node modules does not contain the entire component.
There is only a LICENSE, package.json and readme.md
If I install the previous version, than the folder is fully equiped, but then I have an issue in my angular 18 application => 
The package may have incorrect main/module/exports specified in its package.json.

**Expected behavior:**
I expect the node modules folder to be filled :-)

**Steps to reproduce:**
npm install xml-viewer-component@latest --save

**Other information:**
I was updating my application from angular16 to angular18

**Comment by alex-solx** [comment]
oh you're right, my bad, sorry. Will fix it later today

**Comment by alex-solx** [comment]
fixed in v 0.4.2:
run ```npm install xml-viewer-component@latest --save```
Should work now
