### ISSUE TITLE
Unable to parse the CDATA section

### ISSUE THREAD

**Issue by mkhadiri-obconsulting** [dwarfcoder/xml-viewer-component#4]
Hello ,
I noticed a little problem When the xml content contains the CDATA section.
we get the error "Extra content at the end of the document".
Sometimes on other cases the error is not obtained but the content of the CDATA section remains empty.

The question is: Can we show CDATA section on xml-viewer-component?

Here is an example to reproduce the error. just put this line on your xml content.

"<![CDATA[
      <message> Welcome to TutorialsPoint </message>
   ]] >"

and what we see on the component:

<root>
<parsererror style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black">
<h3>This page contains the following errors:</h3>
<div style="font-family:monospace;font-size:12px">error on line 1 at column 97: Extra content at the end of the document</div>
<h3>Below is a rendering of the page up to the first error.</h3>
</parsererror>
<name required="true">Test XML data</name>
</root>

**Comment by alex-solx** [comment]
Hello, thanks for your report. I'll investigate this issue asap

**Comment by alex-solx** [comment]
I can see a space between ]] and > - this causes "Extra content at the end of the document". You should remove that space from your XML data.
And I've updated this package, use `npm i xml-viewer-component@0.2.1 --save` to work with it. It will show your CDATA sections if they have no errors.

**Comment by mkhadiri-obconsulting** [comment]
Hello,
It works, the CDATA section is displayed. 
Thank you very much for your help and your responsiveness.

**Comment by alex-solx** [comment]
> Hello,
> It works, the CDATA section is displayed.
> Thank you very much for your help and your responsiveness.

That's great.
Feel free to create an issues/pull requests and drop me a line if you want some additional functionality
